const {
  saveRepositoryFiles,
  getRepositoryFiles,
} = require("../database/repository-files.repository");

const {
  saveRepositoryFileContents,
} = require("../database/repository-file-contents.repository");

const {
  saveRepositoryTechnologies,
} = require("../database/repository-tech-stack.repository");

const { buildRepositoryFileTree } = require("./repository-tree.service");

const { readRepositoryFileContents } = require("./repository-content.service");

const {
  detectRepositoryTechnologies,
} = require("./repository-tech-stack.service");

async function indexRepository(repositoryId, clonePath, client) {
  // Step 1: Traverse repository
  const repositoryEntries = await buildRepositoryFileTree(clonePath);

  // Step 2: Save repository structure
  await saveRepositoryFiles(repositoryId, repositoryEntries, client);

  // Step 3: Load saved files
  const repositoryFiles = await getRepositoryFiles(repositoryId, client);

  // Step 4: Read file contents
  const fileContents = await readRepositoryFileContents(
    clonePath,
    repositoryFiles,
  );

  // Step 5: Detect repository technologies
  const technologies = await detectRepositoryTechnologies(
    clonePath,
    repositoryEntries,
  );

  // Step 6: Save repository technologies
  await saveRepositoryTechnologies(repositoryId, technologies, client);

  // Step 7: Save file contents
  await saveRepositoryFileContents(fileContents, client);

  // Step 8:
  // Embeddings are generated by the AI service
  // after the repository import transaction completes.
}

module.exports = {
  indexRepository,
};
